name: open_cdp_flutter_sdk_example
description: Example app for Open CDP Flutter SDK
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  open_cdp_flutter_sdk:
    path: ../
  firebase_core: ^2.24.2
  customer_io: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true 